### ISSUE TITLE
The correct way to extract translations from Twig 

### ISSUE THREAD

**Issue by sabat24** [Coffreo/jms-translation-js-extractor-bundle#1]
I tried to decorate service `Coffreo\JMSTranslationJsExtractorBundle\Extractor\JsFileExtractor` but Symfony gives me information that not such service exists. 
Then I overrided service declaration in config to point out my custom service

```yaml
coffreo.jms_translation.js_extractor.js:
        class:  App\Service\Decorators\JsFileExtractor  <---- my class
        arguments:
            - '@jms_translation.file_source_factory'
            - ['js', 'jsx']
        tags:
            - { name: 'jms_translation.file_visitor' }
```

I tried to extend your class to only override `visitTwigFile` method, but I'm not able to extend `final` class. 

Finally I created a following constructor:

```php
public function __construct(FileSourceFactory $fileSourceFactory, $extensions = null, JsTranslationExtractorInterface $extractor = null)
    {
        $this->fileSourceFactory = $fileSourceFactory;
        $this->jsFileExtractor = new \Coffreo\JMSTranslationJsExtractorBundle\Extractor\JsFileExtractor($fileSourceFactory, $extensions, $extractor);
    }
```

and "extended" your methods like that

```php
public function visitFile(\SplFileInfo $file, MessageCatalogue $catalogue)
    {
        $this->jsFileExtractor->visitFile($file, $catalogue);
    }

   public function visitTwigFile(\SplFileInfo $file, MessageCatalogue $catalogue, Node $ast)
    {
        $translations = $this->jsFileExtractor->findTranslations($file);

        foreach ($translations as $translation) {
            /** @var $translation TranslationString */
            $message = new Message($translation->getMessage(), $translation->getContext('domain') ?: 'messages');
            $message->setDesc($translation->getContext('desc'));
            $message->setDesc($translation->getContext('meaning'));
            $message->addSource($this->fileSourceFactory->create($file, $translation->getLine()));
            $catalogue->add($message);
        }
        $this->jsFileExtractor->visitTwigFile($file, $catalogue, $ast);

    }
```

However it's not the best option. How it should be done?
